 export const colorKeys: Record<string, string> = {
    red: "red",
    blue: "blue",
    green: "green",
    yellow: "yellow",
    orange: "orange",
    pink: "pink",
    black: "black",
    white: "white",
    brown: "brown",
    gray: "gray",
    purple: "purple",
    gold: "gold",
    silver: "silver",
    beige: "beige",
    lime: "lime",
    teal: "teal",
    peach: "peach",
    skyblue: "sky blue",
    maroon: "maroon",
    olive: "olive",
    turquoise: "turquoise",
    coral: "coral",
    mustard: "mustard",
    lavender: "lavender",
    navy: "navy",
    cyan: "cyan",
    magenta: "magenta",
    indigo: "indigo",
    violet: "violet",
    crimson: "crimson",
    salmon: "salmon",
    mint: "mint",
    amber: "amber",
    rust: "rust",
    denim: "denim",
    fuchsia: "fuchsia",
    emerald: "emerald",
    charcoal: "charcoal",
    copper: "copper",
    cream: "cream",
    ivory: "ivory",
    chocolate: "chocolate",
    tan: "tan",
    plum: "plum",
    
};

export const questions: string[] = [
  "Name something that is red in color.",
  "Name something that is blue in color.",
  "Name something that is green in color.",
  "Name something that is yellow in color.",
  "Name something that is orange in color.",
  "Name something that is pink in color.",
  "Name something that is black in color.",
  "Name something that is white in color.",
  "Name something that is brown in color.",
  "Name something that is gray in color.",
  "Name something that is purple in color.",
  "Name something that is gold in color.",
  "Name something that is silver in color.",
  "Name something that is beige in color.",
  "Name something that is lime in color.",
  "Name something that is teal in color.",
  "Name something that is peach in color.",
  "Name something that is maroon in color.",
  "Name something that is olive in color.",
  "Name something that is turquoise in color.",
  "Name something that is coral in color.",
  "Name something that is mustard in color.",
  "Name something that is lavender in color.",
  "Name something that is navy in color.",
  "Name something that is cyan in color.",
  "Name something that is magenta in color.",
  "Name something that is indigo in color.",
  "Name something that is violet in color.",
  "Name something that is crimson in color.",
  "Name something that is salmon in color.",
  "Name something that is mint in color.",
  "Name something that is amber in color.",
  "Name something that is rust in color.",
  "Name something that is denim in color.",
  "Name something that is fuchsia in color.",
  "Name something that is emerald in color.",
  "Name something that is charcoal in color.",
  "Name something that is copper in color.",
  "Name something that is cream in color.",
  "Name something that is ivory in color.",
  "Name something that is tan in color.",
  "Name something that is plum in color.",
];
