export const answers: Record<string, string[]> = {
  red:
[
  "apple",
  "rose",
  "firetruck",
  "strawberry",
  "cherry",
  "blood",
  "tomato",
  "ruby",
  "cardinal",
  "lipstick",
  "stop sign",
  "ladybug",
  "pomegranate",
  "watermelon slice",
  "red pepper",
  "lobster",
  "fire engine",
  "red wine",
  "red velvet cake",
  "red dress",
  "red car",
  "red balloon",
  "red hair",
  "red chili",
  "maple leaf",
  "flag",
  "ribbon",
  "brick",
  "bird",
  "jacket",
  "socks",
  "nail polish",
  "umbrella",
  "scarf",
  "sweater",
  "candy apple",
  "fire hydrant",
  "beetroot",
  "coral",
  "curtain",
  "carpet",
  "paint",
  "marker pen",
  "paper",
  "candle",
  "gloves",
  "shoes",
  "swimsuit",
  "backpack",
  "bell pepper",
  "tulip",
  "velvet",
  "hair dye",
  "heart",
  "firecracker",
  "ruby gem",
  "cupcakes",
  "currant",
  "fireworks",
  "geranium",
  "hibiscus",
  "gerbera",
  "lily",
  "berry",
  "peony",
  "carnation",
  "chestnut",
  "dragon fruit",
  "fairy lights",
  "gladiolus",
  "grape",
  "hawthorn",
  "jelly beans",
  "leather",
  "poppy",
  "radish",
  "raspberry",
  "rhododendron",
  "rosebud",
],
blue:
[
  "sky",
  "ocean",
  "jeans",
  "blueberry",
  "jay",
  "whale",
  "flower",
  "paint",
  "ink",
  "shirt",
  "car",
  "balloon",
  "bird",
  "butterfly",
  "pen",
  "bottle",
  "cup",
  "candy",
  "moon",
  "wave",
  "water",
  "star",
  "notebook",
  "hat",
  "umbrella",
  "scarf",
  "gloves",
  "shoes",
  "dress",
  "tie",
  "socks",
  "jacket",
  "bicycle",
  "curtain",
  "tablecloth",
  "pillow",
  "glass",
  "chair",
  "lamp",
  "poster",
  "book",
  "pool",
  "sea",
  "island",
  "lagoon",
  "lightning",
  "flame",
  "feathers",
  "ice",
  "pebble",
  "jewel",
  "diamond",
  "sapphire",
  "topaz",
  "crystal",
  "rock",
  "metal",
  "ribbon",
  "cactus flower",
  "glass beads",
  "fishing boat",
  "pie",
  "fabric",
  "coral",
  "kayak",
  "jellyfish",
  "mountain",
  "neon light",
  "paintbrush",
  "plastic cup",
  "pool float",
  "rubber duck",
  "seaweed",
  "sweater",
  "tennis ball",
  "toy car",
  "windmill",
  "yarn",
  "yoga mat",
  "zipper",
  "zipline",
  "zombie costume",
  "zodiac sign",
  "zone",
  "zucchini",
  "porcelain",
  "flag",
  "parrot",
],
green:[
  "grass",
  "leaf",
  "frog",
  "cucumber",
  "emerald",
  "spinach",
  "apple",
  "broccoli",
  "pepper",
  "bean",
  "shirt",
  "tie",
  "jacket",
  "shoes",
  "socks",
  "hat",
  "scarf",
  "balloon",
  "bottle",
  "car",
  "couch",
  "pillow",
  "paint",
  "salad",
  "tea",
  "grapes",
  "kiwi",
  "melon",
  "lime",
  "watermelon rind",
  "bean pod",
  "pea",
  "olive",
  "snake",
  "froglet",
  "turtle",
  "parrot",
  "chameleon",
  "caterpillar",
  "tree",
  "bush",
  "moss",
  "algae",
  "kelp",
  "peppercorn",
  "herb",
  "jalapeño",
  "chili",
  "matcha",
  "smoothie",
  "ribbon",
  "candle",
  "crystals",
  "gems",
  "grasshopper",
  "lizard",
  "seaweed",
  "onion",
  "garlic",
  "parsley",
  "cactus",
  "fern",
  "mint",
  "basil",
  "thyme",
  "rosemary",
  "sage",
],
yellow:
[
  "sunflower",
  "banana",
  "lemon",
  "corn",
  "canary",
  "rubber duck",
  "daffodil",
  "mustard",
  "bell pepper",
  "tulip",
  "school bus",
  "pineapple",
  "taxi",
  "squash",
  "buttercup",
  "highlighter",
  "marigold",
  "tennis ball",
  "crayon",
  "jacket (insect)",
  "balloon",
  "cheese",
  "yolk",
  "daisy",
  "chick",
  "glowstick",
],
orange:
[
  "carrot",
  "pumpkin",
  "orange fruit",
  "goldfish",
  "clownfish",
  "tiger lily",
  "cheese puff",
  "traffic cone",
  "basketball",
  "mandarin",
  "coral reef",
  "sweet potato",
  "fall leaf",
  "golden retriever",
  "fire",
  "cantaloupe",
  "orange juice",
  "butternut squash",
  "lobster",
  "pumpkin pie",
  "tabby cat",
  "orange soda",
  "clay",
  "ribbon",
  "chrysanthemum",
  "marigold",
],
pink:
[
  "flamingo",
  "bubblegum",
  "cotton candy",
  "cherry blossom",
  "peony",
  "rose",
  "pink grapefruit",
  "piglet",
  "pink dress",
  "pink lipstick",
  "pink tulip",
  "pink ribbon",
  "pink pearl",
  "pink icing",
  "pink sandal",
  "pink balloon",
  "pink scarf",
  "pink jellybean",
  "pink carnation",
  "pink seashell",
  "pink lemonade",
  "pink socks",
],
black:
[
  "coal",
  "panther",
  "black cat",
  "raven",
  "blackboard",
  "black shoes",
  "black suit",
  "black car",
  "black ink",
  "black coffee",
  "black hat",
  "black hair",
  "black night",
  "black pepper",
  "black umbrella",
  "black gloves",
  "black boots",
  "black dress",
  "black belt",
  "black crow",
],
white:
[
  "snow",
  "cloud",
  "milk",
  "polar bear",
  "white rose",
  "white dove",
  "whiteboard",
  "white shirt",
  "white shoes",
  "white chocolate",
  "white candle",
  "white lily",
  "white swan",
  "white paper",
  "white sand",
  "white cat",
  "white marble",
  "white flag",
  "white rabbit",
  "white towel",
],
brown:
[
  "chocolate",
  "tree bark",
  "coffee bean",
  "bear",
  "cinnamon stick",
  "wood",
  "pine cone",
  "soil",
  "walnut",
  "brown horse",
  "brown bread",
  "leather belt",
  "brown eyes",
  "brown shoes",
  "brown jacket",
  "brown bag",
  "brown fox",
  "brown hat",
  "brown paper",
  "brown sugar",
],
gray:
[
  "elephant",
  "cloudy sky",
  "wolf",
  "asphalt",
  "dove",
  "cement",
  "tin can",
  "mouse",
  "rock",
  "metal",
  "shark",
  "gray sweater",
  "gray hair",
  "gray wolf",
  "gray stone",
  "gray jacket",
  "gray pigeon",
  "gray fog",
  "gray cat",
  "gray seal",
],
purple:
[
  "grape",
  "plum",
  "lavender flower",
  "eggplant",
  "violet",
  "purple tulip",
  "purple shirt",
  "purple balloon",
  "purple grapes",
  "purple cabbage",
  "purple butterfly",
  "purple jellybean",
  "purple amethyst",
  "purple sweater",
  "purple lipstick",
  "purple scarf",
  "purple hat",
  "purple socks",
  "purple cake",
  "purple orchid",
],
gold:
[
  "gold coin",
  "gold ring",
  "gold necklace",
  "gold watch",
  "gold bracelet",
  "gold trophy",
  "gold medal",
  "gold crown",
  "gold leaf",
  "golden retriever",
  "gold bar",
  "gold earrings",
  "gold chain",
  "gold buttons",
  "gold paint",
  "golden sunset",
  "goldfish",
  "gold dust",
  "gold ribbon",
  "gold embroidery",
],
silver:
[
  "silver coin",
  "silver necklace",
  "silver spoon",
  "silver bracelet",
  "silver ring",
  "silver watch",
  "silver car",
  "silver medal",
  "silverware",
  "silver bell",
  "silver button",
  "silver lining",
  "silver fish",
  "silver earrings",
  "silver chain",
  "silver trophy",
  "silver candlestick",
  "silver stars",
  "silver paint",
  "silver wings",
],
beige:
[
  "sand",
  "wheat",
  "camel",
  "oatmeal",
  "linen fabric",
  "tan leather",
  "beige sweater",
  "beige shoes",
  "beige hat",
  "beige curtains",
  "beige couch",
  "beige scarf",
  "beige carpet",
  "beige pants",
  "beige jacket",
  "beige pillow",
  "beige dress",
  "beige sandcastle",
  "beige wall",
  "beige coat",
],
lime:
[
  "lime fruit",
  "lime leaf",
  "lime soda",
  "lime green shirt",
  "lime candy",
  "lime cake",
  "lime ice cream",
  "lime juice",
  "lime bike",
  "lime shoes",
  "lime scarf",
  "lime hat",
  "lime paint",
  "lime pillow",
  "lime backpack",
  "lime bracelet",
  "lime balloon",
  "lime towel",
  "lime socks",
  "lime lamp",
],
teal:
[
  "teal shirt",
  "teal vase",
  "teal scarf",
  "teal umbrella",
  "teal shoes",
  "teal pillow",
  "teal paint",
  "teal car",
  "teal notebook",
  "teal lamp",
  "teal blanket",
  "teal earrings",
  "teal backpack",
  "teal water bottle",
  "teal cushion",
  "teal curtains",
  "teal sweater",
  "teal gloves",
  "teal bicycle",
  "teal towel",
],
peach:
[
  "peach fruit",
  "peach dress",
  "peach lipstick",
  "peach blush",
  "peach cake",
  "peach scarf",
  "peach shirt",
  "peach pillow",
  "peach hat",
  "peach smoothie",
  "peach earrings",
  "peach curtains",
  "peach blanket",
  "peach nail polish",
  "peach backpack",
  "peach balloons",
  "peach lipstick tube",
  "peach cupcake",
  "peach flower",
  "peach soap",
],
skyblue:
[
  "sky",
  "sky blue shirt",
  "sky blue balloon",
  "sky blue car",
  "sky blue paint",
  "sky blue hat",
  "sky blue blanket",
  "sky blue scarf",
  "sky blue curtains",
  "sky blue backpack",
  "sky blue shoes",
  "sky blue towel",
  "sky blue nail polish",
  "sky blue socks",
  "sky blue sweater",
  "sky blue pen",
  "sky blue bicycle",
  "sky blue cup",
  "sky blue chair",
  "sky blue lamp",
],
maroon:
[
  "maroon jacket",
  "maroon shirt",
  "maroon dress",
  "maroon balloon",
  "maroon scarf",
  "maroon lipstick",
  "maroon shoes",
  "maroon car",
  "maroon pillow",
  "maroon paint",
  "maroon sweater",
  "maroon curtains",
  "maroon backpack",
  "maroon hat",
  "maroon gloves",
  "maroon socks",
  "maroon bag",
  "maroon tie",
  "maroon cup",
  "maroon lipstick tube",
],
olive:
[
  "olive fruit",
  "olive oil bottle",
  "olive branch",
  "olive green shirt",
  "olive green jacket",
  "olive drab pants",
  "olive hat",
  "olive gloves",
  "olive green scarf",
  "olive pillow",
  "olive bag",
  "olive green shoes",
  "olive green backpack",
  "olive sweater",
  "olive curtains",
  "olive paint",
  "olive drab backpack",
  "olive green belt",
  "olive salad",
  "olive branch wreath"
],
turquoise:
[
  "turquoise gemstone",
  "turquoise necklace",
  "turquoise earrings",
  "turquoise bracelet",
  "turquoise shirt",
  "turquoise dress",
  "turquoise paint",
  "turquoise car",
  "turquoise scarf",
  "turquoise pillow",
  "turquoise blanket",
  "turquoise water bottle",
  "turquoise backpack",
  "turquoise shoes",
  "turquoise curtains",
  "turquoise balloon",
  "turquoise cup",
  "turquoise hat",
  "turquoise nail polish",
  "turquoise sweater"
],
coral:
[
  "coral reef",
  "coral dress",
  "coral lipstick",
  "coral scarf",
  "coral shirt",
  "coral necklace",
  "coral earrings",
  "coral paint",
  "coral pillow",
  "coral balloon",
  "coral shoes",
  "coral hat",
  "coral bracelet",
  "coral bag",
  "coral curtains",
  "coral sweater",
  "coral cake",
  "coral nail polish",
  "coral backpack",
  "coral cupcake"
],
mustard:
[
  "mustard sauce",
  "mustard seeds",
  "mustard shirt",
  "mustard jacket",
  "mustard paint",
  "mustard dress",
  "mustard scarf",
  "mustard bag",
  "mustard gloves",
  "mustard shoes",
  "mustard hat",
  "mustard balloon",
  "mustard pillow",
  "mustard curtains",
  "mustard sweater",
  "mustard backpack",
  "mustard nail polish",
  "mustard tie",
  "mustard pants",
  "mustard cup"
],
lavender:
[
  "lavender flower",
  "lavender oil",
  "lavender sachet",
  "lavender soap",
  "lavender candle",
  "lavender dress",
  "lavender shirt",
  "lavender scarf",
  "lavender pillow",
  "lavender paint",
  "lavender balloon",
  "lavender bag",
  "lavender gloves",
  "lavender shoes",
  "lavender hat",
  "lavender curtains",
  "lavender sweater",
  "lavender nail polish",
  "lavender backpack",
  "lavender bouquet"
],
navy:
[
  "navy uniform",
  "navy blue shirt",
  "navy blue pants",
  "navy blue jacket",
  "navy tie",
  "navy dress",
  "navy shoes",
  "navy hat",
  "navy balloon",
  "navy blue scarf",
  "navy gloves",
  "navy backpack",
  "navy curtains",
  "navy sweater",
  "navy blue car",
  "navy paint",
  "navy pillow",
  "navy blue socks",
  "navy blue umbrella",
  "navy blue balloon"
],
cyan:
[
  "cyan ink",
  "cyan paint",
  "cyan shirt",
  "cyan dress",
  "cyan balloon",
  "cyan scarf",
  "cyan shoes",
  "cyan hat",
  "cyan backpack",
  "cyan pillow",
  "cyan curtains",
  "cyan sweater",
  "cyan nail polish",
  "cyan gloves",
  "cyan bag",
  "cyan cup",
  "cyan ribbon",
  "cyan balloon bouquet",
  "cyan balloons",
  "cyan yarn"
],
magenta:
[
  "magenta dress",
  "magenta shirt",
  "magenta balloon",
  "magenta scarf",
  "magenta shoes",
  "magenta hat",
  "magenta lipstick",
  "magenta nail polish",
  "magenta paint",
  "magenta pillow",
  "magenta curtains",
  "magenta sweater",
  "magenta gloves",
  "magenta backpack",
  "magenta bag",
  "magenta ribbon",
  "magenta flower",
  "magenta balloon bouquet",
  "magenta yarn",
  "magenta lipstick tube"
],
indigo:
[
  "indigo dye",
  "indigo shirt",
  "indigo jeans",
  "indigo scarf",
  "indigo balloon",
  "indigo gloves",
  "indigo jacket",
  "indigo shoes",
  "indigo dress",
  "indigo curtains",
  "indigo pillow",
  "indigo paint",
  "indigo backpack",
  "indigo bag",
  "indigo nail polish",
  "indigo sweater",
  "indigo hat",
  "indigo balloon bouquet",
  "indigo ribbon",
  "indigo yarn"
],
violet:
[
  "violet flower",
  "violet dress",
  "violet balloon",
  "violet scarf",
  "violet shoes",
  "violet hat",
  "violet nail polish",
  "violet paint",
  "violet pillow",
  "violet curtains",
  "violet gloves",
  "violet sweater",
  "violet backpack",
  "violet bag",
  "violet ribbon",
  "violet yarn",
  "violet lipstick",
  "violet balloon bouquet",
  "violet dress fabric",
  "violet jelly"
],
crimson:
[
  "crimson rose",
  "crimson dress",
  "crimson balloon",
  "crimson scarf",
  "crimson shoes",
  "crimson hat",
  "crimson lipstick",
  "crimson nail polish",
  "crimson paint",
  "crimson pillow",
  "crimson curtains",
  "crimson gloves",
  "crimson sweater",
  "crimson backpack",
  "crimson bag",
  "crimson ribbon",
  "crimson yarn",
  "crimson balloon bouquet",
  "crimson fabric",
  "crimson berries"
],
salmon:
[
  "salmon fish",
  "salmon color shirt",
  "salmon balloon",
  "salmon scarf",
  "salmon shoes",
  "salmon hat",
  "salmon lipstick",
  "salmon nail polish",
  "salmon paint",
  "salmon pillow",
  "salmon curtains",
  "salmon gloves",
  "salmon sweater",
  "salmon backpack",
  "salmon bag",
  "salmon ribbon",
  "salmon yarn",
  "salmon balloon bouquet",
  "salmon fabric",
  "salmon sushi"
],
mint:
[
  "mint leaf",
  "mint candy",
  "mint gum",
  "mint plant",
  "mint tea",
  "mint lotion",
  "mint ice cream",
  "mint chocolate",
  "mint smoothie",
  "mint dress",
  "mint scarf",
  "mint shoes",
  "mint hat",
  "mint nail polish",
  "mint paint",
  "mint pillow",
  "mint gloves",
  "mint sweater",
  "mint backpack",
  "mint ribbon"
],
rose:
[
  "rose flower",
  "rose petal",
  "rose bouquet",
  "rose dress",
  "rose lipstick",
  "rose nail polish",
  "rose scarf",
  "rose shoes",
  "rose hat",
  "rose candle",
  "rose paint",
  "rose pillow",
  "rose gloves",
  "rose sweater",
  "rose backpack",
  "rose ribbon",
  "rose fabric",
  "rose balloon",
  "rose jelly",
  "rose soap"
],
amber:
[
  "amber jewelry",
  "amber necklace",
  "amber earrings",
  "amber bracelet",
  "amber ring",
  "amber pendant",
  "amber resin",
  "amber color glass",
  "amber paint",
  "amber candle",
  "amber scarf",
  "amber shoes",
  "amber dress",
  "amber hat",
  "amber pillow",
  "amber lipstick",
  "amber nail polish",
  "amber ribbon",
  "amber sweater",
  "amber bag"
],
rust:
[
  "rust color metal",
  "rust paint",
  "rust scarf",
  "rust dress",
  "rust shoes",
  "rust hat",
  "rust nail polish",
  "rust lipstick",
  "rust gloves",
  "rust sweater",
  "rust pillow",
  "rust backpack",
  "rust ribbon",
  "rust fabric",
  "rust balloon",
  "rust colored leaves",
  "rust colored wood",
  "rust bucket",
  "rust car",
  "rust stain"
],
denim:
[
  "denim jeans",
  "denim jacket",
  "denim skirt",
  "denim shirt",
  "denim shorts",
  "denim dress",
  "denim bag",
  "denim hat",
  "denim shoes",
  "denim backpack",
  "denim gloves",
  "denim scarf",
  "denim pillow",
  "denim upholstery",
  "denim paint",
  "denim balloon",
  "denim fabric",
  "denim wallet",
  "denim belt",
  "denim upholstery"
],
fuchsia:
[
  "fuchsia flower",
  "fuchsia dress",
  "fuchsia lipstick",
  "fuchsia nail polish",
  "fuchsia scarf",
  "fuchsia shoes",
  "fuchsia hat",
  "fuchsia balloon",
  "fuchsia paint",
  "fuchsia ribbon",
  "fuchsia sweater",
  "fuchsia bag",
  "fuchsia fabric",
  "fuchsia pillow",
  "fuchsia gloves",
  "fuchsia backpack",
  "fuchsia bracelet",
  "fuchsia earrings",
  "fuchsia necklace",
  "fuchsia gown"
],
emerald:
[
  "emerald gemstone",
  "emerald ring",
  "emerald necklace",
  "emerald bracelet",
  "emerald earrings",
  "emerald paint",
  "emerald dress",
  "emerald fabric",
  "emerald shoes",
  "emerald scarf",
  "emerald pillow",
  "emerald balloon",
  "emerald nail polish",
  "emerald lipstick",
  "emerald bag",
  "emerald gloves",
  "emerald backpack",
  "emerald crown",
  "emerald pendant",
  "emerald gown"
],
charcoal:
[
  "charcoal grill",
  "charcoal pencil",
  "charcoal paint",
  "charcoal drawing",
  "charcoal bag",
  "charcoal shoes",
  "charcoal jacket",
  "charcoal fabric",
  "charcoal pillow",
  "charcoal gloves",
  "charcoal scarf",
  "charcoal hat",
  "charcoal balloon",
  "charcoal nail polish",
  "charcoal lipstick",
  "charcoal backpack",
  "charcoal sweater",
  "charcoal pants",
  "charcoal belt",
  "charcoal wall"
],
sky:
[
  "clear sky",
  "sky cloud",
  "sky balloon",
  "sky paint",
  "sky dress",
  "sky scarf",
  "sky umbrella",
  "sky shoes",
  "sky kite",
  "sky pool",
  "sky light",
  "sky mural",
  "sky wallpaper",
  "sky necklace",
  "sky bracelet",
  "sky earrings",
  "sky hat",
  "sky pillow",
  "sky curtains",
  "sky bedspread"
],
copper:
[
  "copper wire",
  "copper pipe",
  "copper coin",
  "copper pot",
  "copper pan",
  "copper bracelet",
  "copper necklace",
  "copper earrings",
  "copper ring",
  "copper statue",
  "copper bowl",
  "copper lamp",
  "copper roof",
  "copper key",
  "copper bell",
  "copper sculpture",
  "copper kettle",
  "copper plate",
  "copper tray",
  "copper mug"
],
cream:
[
  "cream cake",
  "cream ice cream",
  "cream paint",
  "cream lipstick",
  "cream scarf",
  "cream dress",
  "cream sweater",
  "cream pillow",
  "cream sofa",
  "cream curtains",
  "cream gloves",
  "cream shoes",
  "cream hat",
  "cream balloon",
  "cream fabric",
  "cream bag",
  "cream candle",
  "cream wallpaper",
  "cream blanket",
  "cream carpet"
],
ivory:
[
  "ivory tusk",
  "ivory piano keys",
  "ivory necklace",
  "ivory earrings",
  "ivory bracelet",
  "ivory sculpture",
  "ivory paint",
  "ivory fabric",
  "ivory dress",
  "ivory gloves",
  "ivory shoes",
  "ivory bag",
  "ivory chair",
  "ivory candle",
  "ivory curtains",
  "ivory pillow",
  "ivory blanket",
  "ivory hat",
  "ivory balloon",
  "ivory upholstery"
],
chocolate: 
[
  "chocolate bar",
  "chocolate cake",
  "chocolate ice cream",
  "chocolate milk",
  "chocolate chip cookie",
  "chocolate frosting",
  "chocolate candy",
  "chocolate mousse",
  "chocolate truffle",
  "chocolate syrup",
  "chocolate spread",
  "chocolate brownie",
  "chocolate pie",
  "chocolate donut",
  "chocolate fondue",
  "chocolate ganache",
  "chocolate tart",
  "chocolate fudge",
  "chocolate wafer",
  "chocolate shake"
],
tan: 
[
  "tan leather belt",
  "tan shoes",
  "tan jacket",
  "tan hat",
  "tan sofa",
  "tan purse",
  "tan pants",
  "tan gloves",
  "tan backpack",
  "tan boots",
  "tan coat",
  "tan bag",
  "tan wallet",
  "tan couch",
  "tan curtain",
  "tan carpet",
  "tan scarf",
  "tan chair",
  "tan table",
  "tan dress"
],
plum: 
[
  "plum fruit",
  "plum lipstick",
  "plum dress",
  "plum scarf",
  "plum shoes",
  "plum hat",
  "plum nail polish",
  "plum curtain",
  "plum pillow",
  "plum sweater",
  "plum bag",
  "plum cake",
  "plum smoothie",
  "plum paint",
  "plum tie",
  "plum gloves",
  "plum jacket",
  "plum flower",
  "plum nail art",
  "plum blanket"
],
brick: 
[
  "brick wall",
  "brick house",
  "brick chimney",
  "brick path",
  "brick fireplace",
  "brick oven",
  "brick pillar",
  "brick fence",
  "brick pattern",
  "brick tiles",
  "brick garage",
  "brick basement",
  "brick garden",
  "brick courtyard",
  "brick building",
  "brick tower",
  "brick arch",
  "brick foundation",
  "brick mailbox",
  "brick floor"
],
snow: 
[
  "snowflake",
  "snowman",
  "snowball",
  "snow-covered tree",
  "snow boots",
  "snow jacket",
  "snow hat",
  "snow gloves",
  "snow shovel",
  "snowboard",
  "snowmobile",
  "snowy mountain",
  "snow trail",
  "snow angel",
  "snow drift",
  "snow fence",
  "snow sled",
  "snow cave",
  "snow storm",
  "snow park"
],
lemon:
[
  "lemon fruit",
  "lemon juice",
  "lemon cake",
  "lemon tart",
  "lemon candy",
  "lemon tea",
  "lemon pie",
  "lemon zest",
  "lemonade",
  "lemon custard",
  "lemon sauce",
  "lemon balm",
  "lemon lotion",
  "lemon perfume",
  "lemon cleaner",
  "lemon spritz",
  "lemon sherbet",
  "lemon mousse",
  "lemon jelly",
  "lemon syrup"
],
bubblegum:
[
  "bubblegum candy",
  "bubblegum pink shirt",
  "bubblegum balloon",
  "bubblegum machine",
  "bubblegum bubbles",
  "bubblegum lipstick",
  "bubblegum dress",
  "bubblegum nail polish",
  "bubblegum shoes",
  "bubblegum hat",
  "bubblegum gum wrapper",
  "bubblegum scarf",
  "bubblegum toy",
  "bubblegum poster",
  "bubblegum cake",
  "bubblegum ice cream",
  "bubblegum phone case",
  "bubblegum hairband",
  "bubblegum sticker",
  "bubblegum sweater"
],

};
