
export const Ask = () => [
  "Who was your first crush?",
  "Have you ever had a crush on a teacher?",
  "What's your most embarrassing moment at school?",
  "Who's the last person you stalked on Instagram?",
  "Have you ever pretended to be sick to skip school?",
  "What's a secret you've never told anyone?",
  "What's the weirdest dream you've had?",
  "Have you ever lied to your parents about where you were?",
  "Have you ever sent a message you instantly regretted?",
  "Who do you text the most?",
  "What's one thing you wish you could change about yourself?",
  "Who's your celebrity crush?",
  "What's your most used emoji?",
  "Have you ever faked crying?",
  "What's your biggest insecurity?",
  "Have you ever peeked at someone else's test?",
  "Who in this group would you date?",
  "What song do you secretly love?",
  "Have you ever been rejected?",
  "What's the dumbest thing you've ever done on a dare?",
  "If you had a time machine, what moment would you go back to?",
  "What's something you wish your parents never found out?",
  "Have you ever lied to a friend?",
  "What's the most childish show you still watch?",
  "Do you believe in love at first sight?",
  "Have you ever had a crush on a friend's sibling?",
  "What's the most cringe message you've ever sent?",
  "Who's your favorite teacher and why?",
  "Do you sing in the shower?",
  "What's the most trouble you've ever gotten into?",
  "What rumor about you do you wish people would forget?",
  "Have you ever eavesdropped on a conversation?",
  "What's your weirdest habit?",
  "Do you secretly like someone right now?",
  "What's your biggest fear?",
  "Who knows you the best in this group?",
  "What's your dream job?",
  "Would you switch schools if you could?",
  "Do you ever talk to yourself in the mirror?",
  "Have you ever cried during a movie?",
  "Do you have a Finsta (fake Instagram)?",
  "What's your most awkward moment with a crush?",
  "Do you keep a diary or journal?",
  "What's your most overused phrase?",
  "Have you ever had a crush on two people at once?",
  "What's your go-to excuse when you're late?",
  "What's one secret your best friend doesn't know?",
  "Would you date someone younger than you?",
  "Who's the funniest person you know?",
  "What's something that always makes you smile?",
  "Speak in an accent until your next turn.",
  "Do 10 jumping jacks while singing your favorite song.",
  "Text your crush a random emoji.",
  "Post an embarrassing selfie on your story for 10 minutes.",
  "Pretend to be a famous celebrity for 2 minutes.",
  "Try to lick your elbow.",
  "Make a weird face and set it as your profile pic for 5 minutes.",
  "Let someone in the group text anyone in your contacts.",
  "Say the alphabet backwards in 30 seconds.",
  "Do your best animal impression.",
  "Wear socks on your hands for the next 3 turns.",
  "Imitate your favorite teacher.",
  "Do a TikTok dance — even if you don't know one!",
  "Spin around 10 times and try to walk straight.",
  "Eat a spoonful of ketchup or mustard.",
  "Try to touch your nose with your tongue.",
  "Speak only in rhymes for 2 minutes.",
  "Say two nice things about everyone in the room.",
  "Do a dramatic reading of a song lyrics.",
  "Text your mom 'I'm hiding something' and don’t explain.",
  "Say the weirdest thing you’ve ever Googled.",
  "Let someone change your status to something embarrassing.",
  "Do your best evil laugh.",
  "Draw something blindfolded and let everyone guess what it is.",
  "Put your phone on speaker and call your crush.",
  "Pretend to cry for 30 seconds.",
  "Try to moonwalk across the room.",
  "Eat something blindfolded and guess what it is.",
  "Send a voice note singing a random song.",
  "Show the most recent photo in your gallery.",
  "Walk like a model down a pretend runway.",
  "Let the person to your right redo your hairstyle.",
  "Say something in a fake language for one minute.",
  "Do your best impression of your favorite celebrity.",
  "Say the first word that comes to mind for 15 seconds.",
  "Put ice down your back and keep it there for 10 seconds.",
  "Let someone give you a temporary tattoo using a pen.",
  "Speak in slow motion for 2 minutes.",
  "Wrap yourself in toilet paper like a mummy.",
  "Balance a spoon on your nose for 30 seconds.",
  "Swap an item of clothing with someone.",
  "Wear your clothes inside out until your next turn.",
  "Make up a poem on the spot about homework.",
  "Eat a weird food combo someone else chooses.",
  "Try to wink with both eyes.",
  "Hold your breath for as long as you can.",
  "Pretend the floor is lava for the next round.",
  "Call someone and confess you like pineapple on pizza.",
  "Whisper everything you say for 3 minutes.",
  "Walk like a crab until your next turn.",
  "Send a flirty or funny message to someone you’re interested in, without overthinking.",
  "Dance wildly to a song of your choice for one minute in front of others or alone.",
  "Sing a popular song at the top of your lungs, whether in private or in front of friends.",
  "Share an embarrassing story from your past with the group.",
  "Take a shot of a spicy or unusual drink (like hot sauce or vinegar).",
  "Wear a funny or embarrassing outfit or accessory for the next 30 minutes.",
  "Do a dramatic reading of a random text message or email out loud.",
  "Call a friend or family member and do your best impression of a celebrity or cartoon character.",
  "Post a silly or embarrassing photo or story on your social media.",
  "Attempt a new dance move you've never tried before — record it if you want!",
  "Eat something spicy or sour without drinking water for 5 minutes.",
  "Recite a poem or monologue dramatically in front of everyone.",
  "Let someone give you a temporary tattoo (with washable ink or makeup).",
  "Do 50 sit-ups or push-ups in a row.",
  "Hold a plank position for two minutes or longer.",
  "Send a voice message with a funny or flirty message to someone you haven't spoken to in a while.",
  "Try to do a challenging yoga pose or stretch.",
  "Speak in a different accent for the next 5 minutes.",
  "Share your most embarrassing or funny childhood memory.",
  "Send a flirty message to someone you’re interested in.",
  "Perform a fun or sexy dance in front of others or alone.",
  "Give someone a spontaneous massage for five minutes.",
  "Share a secret or something you've never told anyone before with someone you trust.",
  "Kiss someone on the cheek or lips  for at least 10 seconds.",
  "Write a sweet or playful note and hide it somewhere for someone to find.",
  "Take a cute or funny selfie and post it on social media .",
  "Whisper a compliment or a funny comment into someone's ear.",
  "Do a playful or sexy dance for someone .",
  "Share your favorite memorable moment with someone.",
  "Play a quick game of 'truth or dare' with someone and be daring.",
  "Send someone a voice message expressing how much they mean to you.",
  "Cook or prepare a small surprise snack or drink for someone.",
  "Look into someone's eyes for two minutes without speaking.",
  "Recreate a fun or memorable moment you've shared with someone.",
  "Take a shower or bath, or do something relaxing for yourself.",
  "Share a fantasy or a dream you've always wanted to try.",
  "Write a short positive message or quote and read it aloud to someone.",
  "Try a new activity or hobby you've been curious about.",
  "Give someone a playful nickname and use it for the rest of the game.",
];
